name: Build and Upload APK

on:
  push:
    branches:
      - shahzaib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew assembleProductionDebug

      - name: Set version code and version name from gradle file
        run: |
          VERSION_CODE=$(grep "versionCode" app/build.gradle | head -n 1 | sed 's/.*\([0-9]\+\).*/\1/')
          VERSION_NAME=$(grep "versionName" app/build.gradle | head -n 1 | sed 's/.*"\(.*\)".*/\1/')
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Upload APK to Slack
        run: |
          # Construct APK file path dynamically using version code and version name
          APK_PATH="app/build/outputs/apk/production/debug/Newsreel-v${VERSION_CODE}(${VERSION_NAME})-production-debug.apk"
          
          # Check if the file exists and upload it
          if [ -f "$APK_PATH" ]; then
            curl -X POST https://slack.com/api/files.upload \
              -F file=@$APK_PATH \
              -F "channels=android-news-reels" \
              -F "initial_comment=The APK is ready!! Version Code: $VERSION_CODE, Version Name: $VERSION_NAME" \
              -H "Authorization: Bearer ${{ secrets.SLACK_WEBHOOK_URL }}"
          else
            echo "APK not found at $APK_PATH"
            exit 1
          fi
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
